const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Pathfinding.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.EightDir.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{playerhealt: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{player: 0},
	{Mouse: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{bulet: 0},
	{Sprite2: 0},
	{zombiehealt: 0},
	{movement: 0},
	{Pathfinding: 0},
	{zombie: 0},
	{Fade: 0},
	{Sprite4: 0},
	{Anchor: 0},
	{Text: 0},
	{textgameover1: 0},
	{textrestart: 0},
	{Keyboard: 0},
	{Touch: 0},
	{love1: 0},
	{love: 0},
	{love2: 0},
	{bawah: 0},
	{atas: 0},
	{kanan: 0},
	{kiri: 0},
	{Sprite: 0},
	{Audio: 0},
	{love3: 0},
	{TiledBackground2: 0},
	{title: 0},
	{start: 0},
	{homescreen: 0},
	{textgameover2: 0},
	{score: 0},
	{ZombieSpeed: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bulet: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	zombie: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	textgameover1: class extends self.ITextInstance {},
	textrestart: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	love1: class extends self.ISpriteInstance {},
	love: class extends self.ISpriteInstance {},
	love2: class extends self.ISpriteInstance {},
	bawah: class extends self.ISpriteInstance {},
	atas: class extends self.ISpriteInstance {},
	kanan: class extends self.ISpriteInstance {},
	kiri: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	love3: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	title: class extends self.ITextInstance {},
	start: class extends self.ITextInstance {},
	homescreen: class extends self.ITextInstance {},
	textgameover2: class extends self.ITextInstance {}
}